"""
This script will plot the csv generated by the VNA capture script
"""

import numpy as np
import matplotlib.pyplot as plt

# Path to the CSV file
csv_path = r"replace_with_file_path_and_name" # Replace with csv path 


def db20(re, im):
    mag = np.sqrt(re**2 + im**2)
    mag = np.maximum(mag, 1e-15)  # avoid log of zero
    return 20 * np.log10(mag)


# Load numeric data
# File format:
#   0-6   : metadata lines
#   7     : column names
#   8+    : numeric data
data = np.genfromtxt(
    csv_path,
    delimiter=",",
    skip_header=8
)

# Columns
freq_hz = data[:, 0]
s11_re, s11_im = data[:, 1], data[:, 2]
s21_re, s21_im = data[:, 3], data[:, 4]
s12_re, s12_im = data[:, 5], data[:, 6]
s22_re, s22_im = data[:, 7], data[:, 8]

# Convert frequency to GHz
freq_ghz = freq_hz / 1e9

# Convert complex S-parameters to magnitude in dB
s11_db = db20(s11_re, s11_im)
s21_db = db20(s21_re, s21_im)
s12_db = db20(s12_re, s12_im)
s22_db = db20(s22_re, s22_im)

# Plot
plt.figure(figsize=(6.4, 4.8))
plt.plot(freq_ghz, s11_db, label="S11")
plt.plot(freq_ghz, s21_db, label="S21")
plt.plot(freq_ghz, s12_db, label="S12")
plt.plot(freq_ghz, s22_db, label="S22")

plt.title("S-Parameters vs Frequency")
plt.xlabel("Frequency (GHz)")
plt.ylabel("Magnitude (dB)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()