"""
This script will plot the csv generated by the Spectrum capture script
     - This script can take multiple paths to multiple csv files and plot them
"""


import numpy as np
import matplotlib.pyplot as plt

# Path to the CSV file
csv_path = [r"replace_with_csv_path", r"replace_with_csv_path", r"replace_with_csv_path"] # Can do 1 script or multiple

fileNames = ["Mixer_CW_Equipment_LO_Test", "Mixer_CW_Equipment_IF_Test", "Mixer_CW_Equipment_RF_Test"]

def get_data(csv_path):
     data = np.genfromtxt(
          csv_path,
          delimiter=",",
          skip_header=8)
     return data

def find_max(freq_hz,power):
     maxPower = np.max(power)
     maxPowerIndex = np.argmax(power)
     maxFreq = freq_hz(maxPowerIndex)/1e9
     plt.scatter(maxFreq,maxPower)
     plt.annotate("Marker: ",(maxFreq),textcoords='offset points',xytext=(10,10),ha='left')

def plot_save_fig(fileName,data):
     # Columns
     freq_hz = data[:, 0]
     power_dBm = data[:, 1]

     # Convert frequency to GHz
     freq_ghz = freq_hz / 1e9

     # Plot
     plt.figure(figsize=(6.4, 4.8))
     plt.plot(freq_ghz, power_dBm)

     plt.title("Spectrum Capture")
     plt.xlabel("Frequency (GHz)")
     plt.ylabel("Magnitude (dBm)")
     plt.grid(True)
     plt.legend()
     plt.tight_layout()

     maxPower = np.max(power_dBm)
     maxPowerIndex = np.argmax(power_dBm)
     maxFreq = freq_ghz[maxPowerIndex]
     plt.scatter(maxFreq,maxPower,color='red')
     plt.annotate("Marker: {:} dBm".format(maxPower),(maxFreq,maxPower),textcoords='offset points',xytext=(10,0),ha='left',color="green")

     plt.show()




for i in range(0,len(csv_path)):
     data = get_data(csv_path[i])
     plot_save_fig(fileNames[i],data)













