(part "MBT-44+"
    (packageRef "MBT44")
    (interface
        (port "1" (symbPinId 1) (portName "N/C_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RF") (portType INOUT))
        (port "3" (symbPinId 3) (portName "N/C_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "N/C_3") (portType INOUT))
        (port "5" (symbPinId 5) (portName "N/C_4") (portType INOUT))
        (port "6" (symbPinId 6) (portName "RF_+_DC") (portType INOUT))
        (port "7" (symbPinId 7) (portName "N/C_5") (portType INOUT))
        (port "8" (symbPinId 8) (portName "DC") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "139-MBT-44+")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/MBT-44%2b?qs=3pZoU%2F6IRTgNg5fQOAQ8QA%3D%3D")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "MBT-44+")
    (property "Description" "MMIC BIAS TEE,50 10 to 40 GHz , 8L MCLP package ")
    (property "Datasheet_Link" "https://www.minicircuits.com/pdfs/MBT-44+.pdf")
    (property "symbolName1" "MBT-44+")
)
